name: CI

on:
  workflow_dispatch: # for manual running
  pull_request:
jobs:
  Dependencies:
    runs-on: ubuntu-latest
    - name: Download dependencies
      run: ./script1.sh
      
  Compile-test:
    # needs: Dependencies
    runs-on: ubuntu-latest
    # container: https://gasp.app.intel.com/
    steps:
      - name: Check out repositories
        uses: actions/checkout@v3
      - name: Compile and test
        run: |
          CC=clang CXX=clang++ meson builddir
          cd builddir
          meson compile
          meson test