name: CI

on:
  workflow_dispatch: # for manual running
  pull_request:
jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repositories
        uses: actions/checkout@v3
      - name: Download dependencies
        run: |
          chmod +x ./.github/workflows/script1.sh
          ./.github/workflows/script1.sh
      - name: Compile and test
        run: |
          chmod +x ./.github/workflows/script2.sh
          ./.github/workflows/script2.sh
